---
- hosts: all
  roles:
    - name: base

- hosts: getchips
  roles:
    - name: chip

- hosts: players
  roles:
    - name: player
      tags: squeeze

- hosts: lms
  roles:
    - name: logitechmediaserver
      tags: squeeze