---
- name: Set system hostname
  hostname: name="{{ inventory_hostname_short }}"

- name: Set timezone
  timezone:
    name: Europe/Berlin

- name: Update apt repos
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Provide base packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - less
    - net-tools
    - ntp
    - unattended-upgrades
    - vim

- name: Remove obsolete packages
  apt:
    autoclean: yes

- name: Remove obsolete dependencies
  apt:
    autoremove: yes

- name: Provide ntpd configuration
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart ntpd